[package]
name = "netcheck-gui"
version = "0.1.0"
edition.workspace = true
publish = false

[[bin]]
name = "netcheck-gui"
path = "src/main.rs"

[dependencies]
eframe = "0.36.1"
egui = "0.36.1"
egui_extras = "0.36.1"
image = { version = "0.25.10", default-features = false, features = ["png"] }
netstatus = { path = "../netstatus" }
